onlyBuiltDependencies:
  - "@prisma/engines"
  - prisma
  - esbuild
  - sharp
  - protobufjs

ignoredBuiltDependencies:
  - unrs-resolver

allowBuilds:
  '@prisma/engines': true
  esbuild: true
  prisma: true
  sharp: true
